Issue 110: Stats on product pages is invisible
hlxsites/sgws-creative pull request #114
Opened 2023-06-27 21:08 UTC by allentsliu

## Issue

Fix #110 

## 🔗 Test URLs:

- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6
- After: https://issue-110--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6

## 📝 Description:
![Screen Shot 2023-06-27 at 2 07 46 PM](https://github.com/hlxsites/sgws-creative/assets/32020804/263b0717-df93-4046-9f9d-a206f3a4a7d5)

2023-06-27 23:38 UTC, tmathern commented
In the authored page, switch the format from PNG for the hero/poster images to JPEG. THis will help lighthouse scores too.

2023-06-27 23:42 UTC, tmathern requested changes
I would attempt to:
- switch from PNG to JPEG for the image (there is no transparency)
- set a width/height to the image

2023-06-27 23:42 UTC, tmathern commented on scripts/scripts.js
> +      section.append(createOptimizedPicture(image.src, image.alt, true));
You could actually attempt to set a width here, since it would be the width of the page.

2023-06-28 00:19 UTC, allentsliu commented on scripts/scripts.js
> +      section.append(createOptimizedPicture(image.src, image.alt, true));
It seems like the createOptimizedPicture function will insert a width=750 by default `/bloominbrands/p/media_1294bb1e6fb32a045b99efb4d47357dca217f588a.jpeg?width=750&format=jpeg&optimize=medium` 
I have also tried switching from PNG to JPEG for the image, but that doesn't seem to help :(

2023-07-10 16:20 UTC, allentsliu commented
@tmathern  could you approve this PR when you get a chance? Thanks!

2023-07-10 16:38 UTC, tmathern approved these changes

2023-07-10 16:44 UTC, merged