Logo106
hlxsites/sgws-creative pull request #115
Opened 2023-06-28 21:40 UTC by atopper

## Issue

Fix #106 

## 🔗 Test URLs:

- Before: https://main--sgws-creative--hlxsites.hlx.page/drafts/top/column-centered
- After: https://logo106--sgws-creative--hlxsites.hlx.page/drafts/top/column-centered

Original: https://sgcreative.southernglazers.com/bloominbrands/p/2

Authoring: 
First table in link below is the implemented one.  The second suggestion was another idea (simple section).  The last one was a old implementation.
https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/doc.aspx?sourcedoc=%7Be4a56646-8bd9-4f1f-82d6-e237d80b2095%7D&action=edit&cid=f21c1f7a-e0bd-473d-ad59-95d9e2b31a24

## 📝 Description:
Show a logo, some text and link them to an url.
Took suggestion 1 (banner table, 1 row of image & text/url).

2023-06-28 21:55 UTC, tmathern requested changes

2023-06-28 21:55 UTC, tmathern commented on blocks/columns/columns.js
> +        e.stopPropagation();
Is this really needed? What are the side-effect?

2023-06-28 21:55 UTC, tmathern approved these changes

2023-06-29 20:46 UTC, badvision approved these changes
This makes sense, thank you!

2023-06-29 21:00 UTC, atopper commented on blocks/columns/columns.js
> +        e.stopPropagation();
There is no concrete reason - I saw it elsewhere.  But I suppose they could put a banner over some larger, clickable image or something... maybe?  And we wouldn't want the click to propagate to the lower element.  That's what I assumed it was being used for.

2023-06-29 21:02 UTC, atopper commented on blocks/columns/columns.js
> +}
Hey - this shouldn't be here anymore.  I cleaned it up, but it must have reverted back.
Shoot...  I update it.

2023-06-29 21:09 UTC, merged