Block: "people-intro" #153
hlxsites/sgws-creative pull request #164
Opened 2023-07-19 20:37 UTC by atopper

## Issue

Fix #153

## 🔗 Test URLs:

- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/8
- After: https://people-intro153--sgws-creative--hlxsites.hlx.page/bloominbrands/p/8
- After: https://people-intro153--sgws-creative--hlxsites.hlx.page/bloominbrands/fragments/simi-people

Original: https://sgcreative.southernglazers.com/bloominbrands/p/8

## 📝 Description:

2023-07-19 20:42 UTC, tmathern commented
Scaling is off on small screens...
<img width="890" alt="Screenshot 2023-07-19 at 1 42 16 PM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/adfe4832-1046-4d3d-93c5-a5e55326e914">

2023-07-19 20:43 UTC, tmathern commented on blocks/vertical-selector/vertical-selector.js
> +              // setupCharting(block);
```suggestion
```
(Drop the comment)

2023-07-19 20:43 UTC, tmathern commented on scripts/scripts.js
> +    // Expect:
Do we need to keep the comments?

2023-07-19 20:43 UTC, tmathern requested changes
Resizing is off...

2023-07-20 19:05 UTC, atopper commented on scripts/scripts.js
> +    // Expect:
We can always get rid of comments, if you don't think it is helpful.  I thought anyone looking at this in the future would be helped by it.
I assumed the JS/CSS was minimized while being published.  No?

2023-07-20 19:22 UTC, atopper commented on blocks/vertical-selector/vertical-selector.js
> +    if (!showViewer) {
For product 8 (simi), the 3 fragments are not loaded in the vertical selector, but the label is there to click.  This was a quick change to handle the missing fragments nicely - hopefully not needed after all is done but...

2023-07-20 20:01 UTC, tmathern approved these changes

2023-07-20 20:11 UTC, merged