Issue154 - Added animated variant of columns block
hlxsites/sgws-creative pull request #238
Opened 2023-07-29 20:54 UTC by sarav-sgws

This PR is introducing an animated variant to columns block. This will present simi-people slide with images fade-in and text fade-in-left

## Issue

Fix #154 

## 🔗 Test URLs:

- Before:  https://main--sgws-creative--hlxsites.hlx.page/drafts/sarav/simi-people
- After: https://issue-154--sgws-creative--hlxsites.hlx.page/drafts/sarav/simi-people

- Before:  https://main--sgws-creative--hlxsites.hlx.page/drafts/sarav/8
- After: https://issue-154--sgws-creative--hlxsites.hlx.page/drafts/sarav/8

- 
## 📝 Description:

Will play animation for simi-people slide

2023-07-31 16:16 UTC, tmathern requested changes

2023-07-31 16:16 UTC, tmathern commented on blocks/columns/columns.css
> +.columns.animated div>h2 {
```suggestion
.columns.animated div > h2 {
```

2023-07-31 16:16 UTC, tmathern commented on blocks/columns/columns.css
> +.columns.animated div>h4 {
```suggestion
.columns.animated div > h4 {
```

2023-07-31 16:16 UTC, tmathern commented on blocks/columns/columns.js
> +  /* Mark first picture as background-image if class specified */
Add an animation observer in the code if you need the animation to come back for every slide. It's fine to add it for text fading in from left or right, but not for bottom (it can lead to jitter without the viewed-once).

2023-07-31 16:21 UTC, badvision commented on blocks/columns/columns.js
> +    block.querySelector('div > div.picture').classList.add('column-background');
Is this really needed?  I would imagine that any .column-background selector would be equivalent to '.background-image div > div.picture' anyway

2023-08-01 17:51 UTC, sarav-sgws commented on blocks/columns/columns.css
> +.columns.background-image div.picture.column-background {
Hi Tania, the reason for this issue was, this style is driven by `product` page template. My draft page was NOT product template. So I edited [metadata.xlsx](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/southernglazers/sgws-creative/[metadata.xlsx](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/southernglazers/sgws-creative/metadata.xlsx?d=w878dd6be98464f68890a339b592aa9a2&csf=1&web=1&e=PuKfn2)?d=w878dd6be98464f68890a339b592aa9a2&csf=1&web=1&e=PuKfn2), added `product` template for my draft page and now this works.

2023-08-01 19:03 UTC, tmathern requested changes
See comments.

Also - try to get the last image in the second column to stick more to the bottom, so you get nicer image alignment, if possible: 
<img width="1068" alt="Screenshot 2023-08-01 at 11 59 28 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/49773baf-7804-46c4-a069-827046b682fd">

2023-08-01 19:03 UTC, tmathern commented on blocks/columns/columns.css
> +  font-size: 3rem;
Try to have the fonts scale down when the images scale down. We used clamping quite often to get that and prevent fonts being too small to be readable (Lighthouse flags it).

2023-08-01 19:03 UTC, tmathern commented on scripts/scripts.js
> +            if (!target.closest('.columns.animated')) {
I would maybe add an exclusion array on top of the script, so others could be added in the future if needed.

2023-08-01 19:35 UTC, sarav-sgws commented on blocks/columns/columns.css
> +  font-size: 3rem;
thanks. I made second column into flexbox and justified content to evenly space around. now it aligns top and bottom now.

2023-08-01 19:35 UTC, sarav-sgws commented on scripts/scripts.js
> +            if (!target.closest('.columns.animated')) {
created constant and moved out,

2023-08-01 19:57 UTC, tmathern requested changes
One more side-effect to deal with: Those changes break the first slider on https://issue-154--sgws-creative--hlxsites.hlx.page/bloominbrands/p/9, as the stats should be centered.

What I see on https://issue-154--sgws-creative--hlxsites.hlx.page/bloominbrands/p/9 (that's the page with changes from this PR):
<img width="880" alt="Screenshot 2023-08-01 at 12 57 08 PM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/45844070-e7d3-4215-94c2-ec7de6386764">

What it should be (currently on https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/9):
<img width="880" alt="Screenshot 2023-08-01 at 12 57 26 PM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/d05dcf97-6ad4-4d4c-bcb9-c87d3b51c9b7">

2023-08-01 21:16 UTC, sarav-sgws commented
> One more side-effect to deal with: Those changes break the first slider on https://issue-154--sgws-creative--hlxsites.hlx.page/bloominbrands/p/9, as the stats should be centered.
> 
> What I see on https://issue-154--sgws-creative--hlxsites.hlx.page/bloominbrands/p/9 (that's the page with changes from this PR): <img alt="Screenshot 2023-08-01 at 12 57 08 PM" width="880" src="https://user-images.githubusercontent.com/60901087/257627268-45844070-e7d3-4215-94c2-ec7de6386764.png">
> 
> What it should be (currently on https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/9): <img alt="Screenshot 2023-08-01 at 12 57 26 PM" width="880" src="https://user-images.githubusercontent.com/60901087/257627325-d05dcf97-6ad4-4d4c-bcb9-c87d3b51c9b7.png">

thanks for pointing Tania. I was missed specificity. Now corrected it. thanks for pointing

2023-08-01 21:37 UTC, tmathern approved these changes

2023-08-01 21:40 UTC, merged