Global CSS #1
hlxsites/sgws-creative pull request #29
Opened 2023-05-25 14:59 UTC by arumsey

## Issue

Fix #2

## 🔗 Test URLs:

- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
- After: https://global-css--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1

## 📝 Description:

- add constellation theme
- add hero processing
- add fonts

**Word**
<img width="835" alt="image" src="https://github.com/hlxsites/sgws-creative/assets/1004204/8f9cb6ec-a777-44a4-9107-a6f12e41a465">

**HTML**
<img width="1041" alt="image" src="https://github.com/hlxsites/sgws-creative/assets/1004204/be135a89-e3d7-48b5-b87e-a6382ce508e6">

2023-05-25 15:34 UTC, atopper commented on blocks/hero/hero.css
> +  max-width: 500px;
Surprised to see the hero have a max-width.  I thought it would be 100% (or perhaps the 'hero' in my mind is different than the real one).

2023-05-25 15:36 UTC, atopper approved these changes
LGTM - Impressed at your speed, as always.

2023-05-25 15:36 UTC, arumsey commented on blocks/hero/hero.css
> +  max-width: 500px;
The section the hero is in still takes up the full width but the content within the hero section is constrained.

2023-05-25 16:27 UTC, tmathern requested changes

2023-05-25 16:27 UTC, tmathern commented on blocks/hero/hero.css
> +  min-height: 720px;
I think that one should go. In the original website, everything scales down when the screen width-height changes. I don't think there is a min-height involved here:
<img width="1673" alt="Screenshot 2023-05-25 at 9 16 31 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/e7bb453e-7018-4f34-849e-58adad26860c">

2023-05-25 16:27 UTC, tmathern commented on blocks/hero/hero.css
> +main .hero picture:nth-child(3) {
Looks like the text in the hero content also has some margin/padding on top

2023-05-25 16:27 UTC, tmathern commented on blocks/hero/hero.css
> +  min-height: 720px;
(Allthough the version with a min height could be a good one too - it's more like a "presentation"/set of slides)

2023-05-25 16:27 UTC, tmathern commented on scripts/scripts.js
> +  // loadHeader(doc.querySelector('header'));
Will there even be a shared header here? I didn't notice one yet...

2023-05-25 16:27 UTC, tmathern commented on styles/lazy-styles.css
> +  font-weight: 400;
If both fonts have the same weight, don't we want to use a variable?

2023-05-25 16:27 UTC, tmathern commented on styles/styles.css
> +  --primary-color: #0076c0;
Should we already turn this color value into a variable? To support theming?

2023-05-25 16:27 UTC, tmathern commented on styles/styles.css
> +  --secondary-color: #001e5b;
Should we already turn this color value into a variable? To support theming?

2023-05-25 16:44 UTC, allentsliu approved these changes
LGTM!

2023-05-26 12:35 UTC, arumsey commented on blocks/hero/hero.css
> +  min-height: 720px;
THere needs to be a height set but maybe it should be a percentage. I agree that the current value does not behave teh same as the current site design.

2023-05-26 12:40 UTC, arumsey commented on styles/lazy-styles.css
> +  font-weight: 400;
What would the variable be?

2023-05-26 12:41 UTC, arumsey commented on styles/styles.css
> +  --primary-color: #0076c0;
`--primary-color` is the theme var that is being overriden for the `constellation` theme.

2023-05-26 12:54 UTC, arumsey commented on blocks/hero/hero.css
> +  min-height: 720px;
The current sites uses a lot of JS to set the viewport scale via a CSS transform.

```
transform: scale(1.01484, 1.01484);
```

We need to figure out if this behaviour needs to carry forward to the Franklin site or if responsive breakpoints would be permitted.

2023-05-26 19:38 UTC, merged

2023-05-26 19:58 UTC, arumsey commented
Fixes #1