stats block
hlxsites/sgws-creative pull request #51
Opened 2023-06-05 21:44 UTC by allentsliu

## Issue

Fix #8 

## 🔗 Test URLs:

- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
- After: https://stats-block--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1

## 📝 Description:
- created a stats block for the main bloominbrands page
- created a stats-fragment block and the following fragment variables for the product pages
  --stats-text-h2
  --stats-text-p
  --stats-border-background-color
  --stats-border-filter
  --stats-text-background-color
  --stats-background-image

![Screen Shot 2023-06-05 at 2 38 29 PM](https://github.com/hlxsites/sgws-creative/assets/32020804/1a8f1e60-6a34-40c5-b054-fee13bb403d0)
![Screen Shot 2023-06-05 at 2 38 40 PM](https://github.com/hlxsites/sgws-creative/assets/32020804/ecd9eab8-7833-46f5-9699-2f059163d5d1)
![Screen Shot 2023-06-05 at 2 38 51 PM](https://github.com/hlxsites/sgws-creative/assets/32020804/b8b4a56c-1969-40fb-bad0-87d5ffd8cef1)
![Screen Shot 2023-06-05 at 2 39 01 PM](https://github.com/hlxsites/sgws-creative/assets/32020804/ad7a6af4-32b7-4f18-b7d7-30b471dff330)

2023-06-05 22:51 UTC, tmathern commented on blocks/columns/columns.css
> +  background-image: linear-gradient(0deg, #0076C0 0%, #001E5B 100%);
Can we use rgb function here instead, for the colors?

2023-06-05 22:54 UTC, tmathern requested changes
The height of the stats doesn't resize/rescale on window resize (the size is fixed in pixels currently in the PR's CSS). Once this is fixed we'll be good!

2023-06-05 22:54 UTC, tmathern commented on blocks/columns/columns.css
> +  height: 208px;
The height should be relative too, to scale on resize

2023-06-05 22:54 UTC, tmathern commented on blocks/columns/columns.css
> +  filter: drop-shadow(#00000080 0 4px 1px);
Is it used only once? Otherwise I'd suggest using a variable.

2023-06-05 22:54 UTC, tmathern commented on styles/styles.css
> +  --stats-text-h2: var(--secondary-color);
You can also define vars in the columns.css file if they're sued only there.

2023-06-05 23:23 UTC, arumsey commented on blocks/columns/columns.css
> +  background-image: linear-gradient(0deg, #0076C0 0%, #001E5B 100%);
Why?

2023-06-05 23:26 UTC, arumsey commented on styles/styles.css
> +  --stats-text-h2: var(--secondary-color);
I also prefer separating var names from their implmentation. So instead of `h2` and `p` you could use `--stats-body-text-color` and `--stats-heading-text-color`

2023-06-05 23:27 UTC, arumsey commented on blocks/columns/columns.css
> +  column-gap: 0.5rem;
Does the column gap stay constant? Use `px` if that is the case.

2023-06-05 23:28 UTC, arumsey commented on blocks/columns/columns.css
> +  display: grid;
Using existing `display: flex` like rest of `columns` block wasn't possible?

2023-06-05 23:37 UTC, arumsey commented
I noticed you included the bottom border as part of the stats block. I was hoping the border treatment could be added as default content above and below the `slides` block or potentially part of the slides block. Prefferably, `stats` should just be added under the slides block and not have to worry about borders.

<img width="649" alt="image" src="https://github.com/hlxsites/sgws-creative/assets/1004204/5ad978ea-c0d2-4f69-a917-d778da33eae0">

2023-06-05 23:37 UTC, allentsliu commented on blocks/columns/columns.css
> +  background-image: linear-gradient(0deg, #0076C0 0%, #001E5B 100%);
I can't seem to use the rgb function here as it will return the **Expected modern color-function notation**  lint error

2023-06-05 23:37 UTC, allentsliu commented on blocks/columns/columns.css
> +  height: 208px;
thx.. I will fix it.

2023-06-05 23:38 UTC, allentsliu commented on blocks/columns/columns.css
> +  filter: drop-shadow(#00000080 0 4px 1px);
yes, it's only used once

2023-06-05 23:39 UTC, arumsey commented on blocks/columns/columns.css
> +.columns.stats-fragment {
What do we have `stats` and `stats-fragment` styles? This really isn't a fragment and for an author the naming should be simple. Is it possible just to just use `stats` as the class name?

2023-06-05 23:41 UTC, allentsliu commented on styles/styles.css
> +  --stats-text-h2: var(--secondary-color);
I thought we need to put all the theme vars in the same location. If it is not the requirement, I will move them to columns.css file. I will rename the var names too. Thanks!

2023-06-06 00:06 UTC, allentsliu commented on blocks/columns/columns.css
> +.columns.stats-fragment {
I created two variation for the `stats` block because the one on the main page has different style than the `stats` block in the product section. (i..e they have different height, margin/padding, gap/no gap, background etc)
If not separating them, it will require more parameters/variables in the theme to configure them which makes authoring more complex. 
Is there a way to use the same `stats` block for different style without introducing too many variables?

2023-06-06 00:11 UTC, arumsey commented on blocks/columns/columns.css
> +.columns.stats-fragment {
You have a couple options. If the styling of the stats block is dependent on the page it is being used you could leverage the template or maybe theme classes added to the body. If it is dependent on what other blocks are in its section you could leverage any of the `blockname-container` classes on the section. Finally, if it is truly author dependent you could add a second modifer to the block.

You could have `Columns (stats)` and maybe `Colomns (stats, large)` or `Columns (status, wide)`. Whatever distinguishes the difference from the base stats block.

2023-06-06 00:26 UTC, arumsey commented on styles/styles.css
> +  --stats-text-h2: var(--secondary-color);
Not every CSS var needs to be exposed as a theme var. So if you don't need/want your vars overwritten by a theme you can define them in `columns.css`

2023-06-06 00:33 UTC, allentsliu commented on blocks/columns/columns.css
> +.columns.stats-fragment {
Thanks for the tips Anthony. It seems like the stats block is author dependent (i.e the author needs to configure text color and background for different products). I will give `Columns (stats, wide)` a try.

2023-06-06 00:48 UTC, allentsliu commented
@arumsey  I wasn't sure where to put the border image. Is it a standard to put all the image in a `Slide` block? 
In case there is a top and bottom border (i.e in the outback steakhouse tabview). Is below the correct change in the word doc?
![Screen Shot 2023-06-05 at 5 47 24 PM](https://github.com/hlxsites/sgws-creative/assets/32020804/4178b7b2-2862-4381-bba0-a2b7c6561d66)

2023-06-06 00:57 UTC, arumsey commented
> @arumsey I wasn't sure where to put the border image. Is it a standard to put all the image in a `Slide` block? In case there is a top and bottom border (i.e in the outback steakhouse tabview). Is below the correct change in the word doc? ![Screen Shot 2023-06-05 at 5 47 24 PM](https://user-images.githubusercontent.com/32020804/243515830-4178b7b2-2862-4381-bba0-a2b7c6561d66.png)

I haven't fully thought it through but I was hoping the border images could be placed in between blocks as default content since they aen't directly related to the block.

<img width="624" alt="image" src="https://github.com/hlxsites/sgws-creative/assets/1004204/fe0e6d79-1241-47fc-9564-ff9166b700c4">

2023-06-06 16:11 UTC, allentsliu commented
got it.. I will give it a try.

2023-06-07 19:43 UTC, arumsey commented on styles/styles.css
> +  --stats-background-image: none;
These need to move to `stats.css`

2023-06-07 19:43 UTC, arumsey commented on styles/styles.css
> +}
We can't have brand specfic styles here since that is authored content and we have no idea what the brand names may be. These can stay for now but I think we need to re-think how borders can be managed in a more generic way.

https://github.com/hlxsites/sgws-creative/issues/56

2023-06-07 19:43 UTC, arumsey commented on blocks/columns/columns.css
> +.columns.stats-wide > div {
If this block is authored as `Columns (stats, wide)` then the selector should be `.columns.stats.wide`.

2023-06-07 20:03 UTC, allentsliu commented on styles/styles.css
> +  --stats-background-image: none;
currently, there is no stats.css file. Should I create a subfolder `stats` under the `block` folder and put the `stats.css` file in it?

2023-06-07 20:09 UTC, allentsliu commented on styles/styles.css
> +}
ok. One way I can think of is to create variables for the border styling in the theme.json for each brand. But it may cause the number of variables in theme.json gets very large very quickly.

2023-06-07 20:22 UTC, arumsey commented on styles/styles.css
> +}
That really isn't the point of `theme.json`. It is meant to be somewhere where a generic set of colors and fonts can be defined to match a particular brand. Blocks can then use these generic values however they see fit. We still need to determine what the minimum set of theme vars needs to be. I am hoping we don't get o the point where every block defines its own unique vars which can then be set via the `theme.json`. That sounds like it would get very difficult to author. Instead blocks should figure out as many variations they need based off of the small set of theme vars exposed on every page. 

For borders lets figure out how many variations we need to support and see if we can come with non-brand specific way of defining them. Just because a particular border is on the `outback` tab today doesn't mean that same border style couldn't be used again on some future non-outback tab.

2023-06-07 20:23 UTC, arumsey commented on styles/styles.css
> +  --stats-background-image: none;
Ooops, sorry. `columns.css` since that is where I am assuming the `--stats-*` vars are used.

eg.
```
.columns {
  --stats-heading-text-color: var(--secondary-color);
  --stats-body-text-color: var(--text-color);
  --stats-text-background-color: transparent;
  --stats-background-image: none;
}
```

2023-06-07 21:21 UTC, allentsliu commented on styles/styles.css
> +  --stats-background-image: none;
I have removed the variables since they are defined in the theme.json.

2023-06-07 21:23 UTC, allentsliu commented on styles/styles.css
> +}
ok.. currently, we have two variations (1 for carrabbas and 1 for outback)

2023-06-07 21:24 UTC, allentsliu commented on blocks/columns/columns.css
> +.columns.stats-wide > div {
thanks for the tips Anthony. Using unset fixed the issue.

2023-06-08 14:09 UTC, arumsey commented on styles/styles.css
> +  --stats-background-image: none;
stats vars should not be defined in theme.json either. I will log a new issue to clean that up.

https://github.com/hlxsites/sgws-creative/issues/57

2023-06-08 14:10 UTC, arumsey approved these changes
I have logged some follow up issues but I don't want to block this PR longer that it needs to be.

2023-06-08 16:28 UTC, allentsliu commented
@tmathern thanks. I created an issue for the it. https://github.com/hlxsites/sgws-creative/issues/58

2023-06-08 16:28 UTC, merged