Pairs-with view #52
hlxsites/sgws-creative pull request #94
Opened 2023-06-20 21:52 UTC by atopper

## Issue

Fix #52

## 🔗 Test URLs:

- Before: https://main--sgws-creative--hlxsites.hlx.page/drafts/top/slides-pairswith
- After: https://paris-with-52--sgws-creative--hlxsites.hlx.page/drafts/top/slides-pairswith

## 📝 Description:
Allow the user to author a "pairs-with" view in the slides.

2023-06-20 21:56 UTC, atopper commented on blocks/slides/slides.css
> -@media (prefers-reduced-motion: no-preference) {
This style made the buttons go opaque for me (bad default with no theme?).  I'm not sure 'reduce' is good either though.

2023-06-20 22:19 UTC, tmathern requested changes
2 things: 
- Could you create a draft of the landing page in which this is used?
- It would be nice if the "pairs with" has the same height as the underlying slide, so nobody becomes sea-sick. (This may need js magic).

2023-06-20 22:19 UTC, tmathern commented on blocks/slides/slides.css
> -@media (prefers-reduced-motion: no-preference) {
ACK. On which browser?

2023-06-20 23:40 UTC, atopper commented on blocks/slides/slides.css
> -@media (prefers-reduced-motion: no-preference) {
Windows, Chrome.  If the user hasn't specified that motion should be reduced, the value becomes "no-preference".   `Reduce` means to keep it to a minimum.

2023-06-21 12:17 UTC, atopper commented
> It would be nice if the "pairs with" has the same height as the underlying slide, so nobody becomes sea-sick. (This may need js magic).

This makes sense visually, but what if the 'pairs-with' text is much larger than the text in the first view?  Do I make the origin view a lot taller, which would look weird with the empty space?  Or do I limit the 'pairs with' view, and add scroll bars, which would look weird in this presentation model?  Or do we lock the height, and assume their text will be authored properly to fit nicely (which it seems like they have)?

2023-06-21 16:15 UTC, atopper commented
@tmathern  I'm trying to make a landing page with my changes, but here's my branch using the original /p/1 doc
https://pairs_with_52--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1

I'm having trouble copying the 1.docx to my draft.  I believe some of the links, themes, etc. are all lost.

2023-06-21 18:24 UTC, tmathern approved these changes

2023-06-21 20:52 UTC, merged